services:
  db:
    image: mysql:8
    container_name: mysql-trabalho
    environment:
      MYSQL_DATABASE: devweb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rede-trabalho
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-trabalho
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/devweb
      - CHAVE_SECRETA=${CHAVE_SECRETA:-minha_chave_super_secreta_jwt_1234567890}
    networks:
      - rede-trabalho
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:

networks:
  rede-trabalho:
    driver: bridge